#!/bin/sh
#
# git prepare-commit-msg hook

# check if commit is new commit
if [ "x$2" != "x" ]; then
    exit
fi

JIRA_PROJECT="$(git config --get jira.project)"

if [[ "$JIRA_PROJECT" == "" ]]; then
    echo -e "You must set the JIRA project Key:\ngit config --add jira.project <Project Key>"
fi

# issue key matched from branch prefix, prepend to commit message
TEMP=`mktemp /tmp/commitmsg-XXXXX`
(echo "$JIRA_PROJECT- #time 0h 0m; cat $1) > $TEMP
cat $TEMP > $1
rm $TEMP
